version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            python -m playwright install
      - run:
          name: Ejecutar pruebas
          command: pytest tests/

workflows:
  version: 2
  login-tests:
    jobs:
      - test
